version: "3"
services:
  app_node:
    container_name: app_node
    build: ./
    env_file:
      - ./.env
    ports:
      - 4002:${PORT}
    depends_on:
      - mongoDB
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

  mongoDB:
    image: "mongo"
    container_name: mongoDB
    env_file:
      - ./.env
    ports:
      - 27018:${MONGO_PORT}
    restart: always
    volumes:
      - mongoDB:/var/lib/mongodb/data/db
    environment:
      - MONGODB_URI=${MONGO_URI}

volumes:
  node_modules:
  mongoDB:
